import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        optimaliq: {
          DEFAULT: "#1A73E8",
        },
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        }
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
      },
      typography: {
        optimaliq: {
          css: {
            '--tw-prose-body': '#374151',
            '--tw-prose-headings': '#111827',
            '--tw-prose-links': '#1A73E8',
            '--tw-prose-bold': '#111827',
            '--tw-prose-counters': '#6B7280',
            '--tw-prose-bullets': '#D1D5DB',
            '--tw-prose-hr': '#E5E7EB',
            '--tw-prose-quotes': '#111827',
            '--tw-prose-quote-borders': '#E5E7EB',
            '--tw-prose-captions': '#6B7280',
            '--tw-prose-code': '#111827',
            '--tw-prose-pre-code': '#E5E7EB',
            '--tw-prose-pre-bg': '#1F2937',
            '--tw-prose-th-borders': '#D1D5DB',
            '--tw-prose-td-borders': '#E5E7EB',
            '--tw-prose-invert-body': '#D1D5DB',
            '--tw-prose-invert-headings': '#FFF',
            '--tw-prose-invert-links': '#60A5FA',
            '--tw-prose-invert-bold': '#FFF',
            '--tw-prose-invert-counters': '#9CA3AF',
            '--tw-prose-invert-bullets': '#4B5563',
            '--tw-prose-invert-hr': '#374151',
            '--tw-prose-invert-quotes': '#F3F4F6',
            '--tw-prose-invert-quote-borders': '#374151',
            '--tw-prose-invert-captions': '#9CA3AF',
            '--tw-prose-invert-code': '#FFF',
            '--tw-prose-invert-pre-code': '#D1D5DB',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': '#4B5563',
            '--tw-prose-invert-td-borders': '#374151',
            color: 'var(--tw-prose-body)',
            lineHeight: '1.75',
            '> * + *': {
              marginTop: '1.25em',
            },
            p: {
              marginTop: '1.25em',
              marginBottom: '1.25em',
              fontSize: '1.125rem',
              lineHeight: '1.75',
              color: 'var(--tw-prose-body)',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            '[class~="lead"]': {
              color: 'var(--tw-prose-body)',
              fontSize: '1.25rem',
              lineHeight: '1.6',
              marginTop: '2em',
              marginBottom: '2em',
            },
            blockquote: {
              fontWeight: '500',
              fontStyle: 'italic',
              color: 'var(--tw-prose-quotes)',
              borderLeftWidth: '0.25rem',
              borderLeftColor: '#1A73E8',
              quotes: '"\\201C""\\201D""\\2018""\\2019"',
              marginTop: '1.6em',
              marginBottom: '1.6em',
              paddingLeft: '1em',
              paddingRight: '1em',
              paddingTop: '1em',
              paddingBottom: '1em',
              backgroundColor: '#F8FAFC',
              borderRadius: '0.5rem',
            },
            h1: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '800',
              fontSize: '2.25rem',
              lineHeight: '1.1111111',
              marginTop: '0',
              marginBottom: '0.8888889em',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            h2: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '700',
              fontSize: '1.875rem',
              lineHeight: '1.3333333',
              marginTop: '2em',
              marginBottom: '1em',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            h3: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '600',
              fontSize: '1.5rem',
              lineHeight: '1.6',
              marginTop: '1.6em',
              marginBottom: '0.6em',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            h4: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '600',
              marginTop: '1.5em',
              marginBottom: '0.5em',
              lineHeight: '1.5',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            figure: {
              marginTop: '2em',
              marginBottom: '2em',
            },
            'figure > *': {
              marginTop: '0',
              marginBottom: '0',
            },
            figcaption: {
              color: 'var(--tw-prose-captions)',
              fontSize: '0.875rem',
              lineHeight: '1.4285714',
              marginTop: '0.8571429em',
            },
            code: {
              color: 'var(--tw-prose-code)',
              fontWeight: '600',
              fontSize: '0.875rem',
              fontFamily: 'ui-monospace, SFMono-Regular, "Menlo", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
            },
            'code::before': {
              content: '"`"',
            },
            'code::after': {
              content: '"`"',
            },
            'a code': {
              color: 'var(--tw-prose-links)',
            },
            pre: {
              color: 'var(--tw-prose-pre-code)',
              backgroundColor: 'var(--tw-prose-pre-bg)',
              overflowX: 'auto',
              fontWeight: '400',
              fontSize: '0.875rem',
              lineHeight: '1.7142857',
              marginTop: '1.7142857em',
              marginBottom: '1.7142857em',
              borderRadius: '0.375rem',
              paddingTop: '0.8571429em',
              paddingRight: '1.1428571em',
              paddingBottom: '0.8571429em',
              paddingLeft: '1.1428571em',
            },
            'pre code': {
              backgroundColor: 'transparent',
              borderWidth: '0',
              borderRadius: '0',
              padding: '0',
              fontWeight: '400',
              color: 'inherit',
              fontSize: 'inherit',
              fontFamily: 'inherit',
              lineHeight: 'inherit',
            },
            'pre code::before': {
              content: 'none',
            },
            'pre code::after': {
              content: 'none',
            },
            table: {
              width: '100%',
              tableLayout: 'auto',
              textAlign: 'left',
              marginTop: '2em',
              marginBottom: '2em',
              fontSize: '0.875rem',
              lineHeight: '1.7142857',
            },
            thead: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '600',
              borderBottomWidth: '1px',
              borderBottomColor: 'var(--tw-prose-th-borders)',
            },
            'thead th': {
              verticalAlign: 'bottom',
              paddingRight: '0.5714286em',
              paddingBottom: '0.5714286em',
              paddingLeft: '0.5714286em',
            },
            'tbody tr': {
              borderBottomWidth: '1px',
              borderBottomColor: 'var(--tw-prose-td-borders)',
            },
            'tbody tr:last-child': {
              borderBottomWidth: '0',
            },
            'tbody td': {
              verticalAlign: 'baseline',
              padding: '0.5714286em',
            },
            tfoot: {
              borderTopWidth: '1px',
              borderTopColor: 'var(--tw-prose-th-borders)',
            },
            'tfoot td': {
              verticalAlign: 'top',
              paddingRight: '0.5714286em',
              paddingTop: '0.5714286em',
              paddingLeft: '0.5714286em',
            },
            '> ul > li': {
              position: 'relative',
              paddingLeft: '1.75em',
              marginTop: '0.5em',
              marginBottom: '0.5em',
              fontSize: '1.125rem',
              lineHeight: '1.75',
              color: 'var(--tw-prose-body)',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            '> ul > li::marker': {
              width: '0.375em',
              height: '0.375em',
              marginTop: '0.875em',
              marginLeft: '-1.25em',
              backgroundColor: '#1A73E8',
              borderRadius: '50%',
            },
            '> ol > li': {
              position: 'relative',
              paddingLeft: '1.75em',
              marginTop: '0.5em',
              marginBottom: '0.5em',
              fontSize: '1.125rem',
              lineHeight: '1.75',
              color: 'var(--tw-prose-body)',
              fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            },
            '> ol > li::marker': {
              fontWeight: '400',
              color: 'var(--tw-prose-counters)',
            },
            'ul ul, ul ol, ol ul, ol ol': {
              marginTop: '0.75em',
              marginBottom: '0.75em',
            },
            li: {
              marginTop: '0.5em',
              marginBottom: '0.5em',
            },
            hr: {
              borderColor: 'var(--tw-prose-hr)',
              borderTopWidth: 1,
              marginTop: '3em',
              marginBottom: '3em',
            },
            'hr + *': {
              marginTop: '0',
            },
            'h2 + *': {
              marginTop: '0',
            },
            'h3 + *': {
              marginTop: '0',
            },
            'h4 + *': {
              marginTop: '0',
            },
            'h6 + *': {
              marginTop: '0',
            },
            'thead th:first-child': {
              paddingLeft: '0',
            },
            'thead th:last-child': {
              paddingRight: '0',
            },
            'tbody td:first-child, tfoot td:first-child': {
              paddingLeft: '0',
            },
            'tbody td:last-child, tfoot td:last-child': {
              paddingRight: '0',
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
} satisfies Config;
