-- Drop existing columns
ALTER TABLE sales_performance_assessment
DROP COLUMN IF EXISTS how_b5d8e7,
DROP COLUMN IF EXISTS do_b7cc0a,
DROP COLUMN IF EXISTS how_fee95e,
DROP COLUMN IF EXISTS who_5d9558,
DROP COLUMN IF EXISTS how_454fc5,
DROP COLUMN IF EXISTS which_01150c,
DROP COLUMN IF EXISTS how_142ca2,
DROP COLUMN IF EXISTS how_2c42b7,
DROP COLUMN IF EXISTS how_79028c,
DROP COLUMN IF EXISTS how_47b050,
DROP COLUMN IF EXISTS how_12d26c,
DROP COLUMN IF EXISTS how_1f869b,
DROP COLUMN IF EXISTS how_c8eb2a,
DROP COLUMN IF EXISTS how_64a8d1,
DROP COLUMN IF EXISTS how_7d8dcb,
DROP COLUMN IF EXISTS how_0fa447,
DROP COLUMN IF EXISTS how_a76658,
DROP COLUMN IF EXISTS how_5589a0,
DROP COLUMN IF EXISTS how_92a11d,
DROP COLUMN IF EXISTS how_1e24f7,
DROP COLUMN IF EXISTS how_b5793e,
DROP COLUMN IF EXISTS how_140f94,
DROP COLUMN IF EXISTS how_3a6376,
DROP COLUMN IF EXISTS how_4cd27c,
DROP COLUMN IF EXISTS how_68cbdb,
DROP COLUMN IF EXISTS how_d30c39,
DROP COLUMN IF EXISTS how_4a7d74,
DROP COLUMN IF EXISTS how_c7b9f7,
DROP COLUMN IF EXISTS what_84c5f2,
DROP COLUMN IF EXISTS how_8f9d2a,
DROP COLUMN IF EXISTS how_1a3b4c,
DROP COLUMN IF EXISTS how_5d6e7f,
DROP COLUMN IF EXISTS how_2d3e4f,
DROP COLUMN IF EXISTS how_4d1ff3,
DROP COLUMN IF EXISTS how_fe4a96,
DROP COLUMN IF EXISTS how_2e3f4g,
DROP COLUMN IF EXISTS how_5f6g7h,
DROP COLUMN IF EXISTS how_8g9h0i,
DROP COLUMN IF EXISTS how_4i5j6k,
DROP COLUMN IF EXISTS how_1579c0,
DROP COLUMN IF EXISTS how_ed3928,
DROP COLUMN IF EXISTS how_6j7k8l,
DROP COLUMN IF EXISTS how_9k0l1m,
DROP COLUMN IF EXISTS how_2l3m4n,
DROP COLUMN IF EXISTS how_8n9o0p,
DROP COLUMN IF EXISTS how_18515e,
DROP COLUMN IF EXISTS how_70b7b8,
DROP COLUMN IF EXISTS how_1p2q3r,
DROP COLUMN IF EXISTS how_4q5r6s,
DROP COLUMN IF EXISTS how_7r8s9t,
DROP COLUMN IF EXISTS how_3t4u5v,
DROP COLUMN IF EXISTS how_136dcf,
DROP COLUMN IF EXISTS how_e9af60,
DROP COLUMN IF EXISTS how_6v7w8x,
DROP COLUMN IF EXISTS how_9w0x1y,
DROP COLUMN IF EXISTS how_2x3y4z,
DROP COLUMN IF EXISTS how_8z9a0b;

-- Add JSONB column for answers
ALTER TABLE sales_performance_assessment
ADD COLUMN answers JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Create index on answers for better query performance
CREATE INDEX idx_sales_performance_assessment_answers ON sales_performance_assessment USING gin (answers);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_sales_performance_assessment_updated_at
    BEFORE UPDATE ON sales_performance_assessment
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column(); 